DROP TABLE IF EXISTS BOOKING;

CREATE TABLE BOOKING (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  bookingName VARCHAR(250) NOT NULL,
  companyName VARCHAR(250) NOT NULL,
  timeFrom TIMESTAMP,
  timeTo TIMESTAMP,
  bookingState ENUM('PENDING', 'ACCEPTED') NOT NULL
);