DROP TABLE IF EXISTS BOOKING;

CREATE TABLE BOOKING (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  booking_name VARCHAR(250),
  company_name VARCHAR(250) NOT NULL,
  full_name VARCHAR(250) NOT NULL,
  time_from TIMESTAMP,
  time_to TIMESTAMP,
  booking_state ENUM('PENDING', 'ACCEPTED') NOT NULL
);